//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthoritySTS.LocalizationResources.Models.AccountViewModels {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class VerifyOTPViewModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal VerifyOTPViewModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthoritySTS.LocalizationResources.Models.AccountViewModels.VerifyOTPViewModel", typeof(VerifyOTPViewModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter One Time Password (OTP).
        /// </summary>
        internal static string EnterOneTimePass {
            get {
                return ResourceManager.GetString("EnterOneTimePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter OTP.
        /// </summary>
        internal static string EnterOTP {
            get {
                return ResourceManager.GetString("EnterOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the OTP here.
        /// </summary>
        internal static string EnterOTPHere {
            get {
                return ResourceManager.GetString("EnterOTPHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP.
        /// </summary>
        internal static string OTP {
            get {
                return ResourceManager.GetString("OTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;OTP&lt;span class=&quot;text-danger&quot;&gt;*&lt;/span&gt;&lt;/span&gt;.
        /// </summary>
        internal static string OTP_Field {
            get {
                return ResourceManager.GetString("OTP_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Password(OTP) has been sent to your {0}. Please enter the same here to reset password.
        /// </summary>
        internal static string Otp_Sent_Enter_Reset_Password {
            get {
                return ResourceManager.GetString("Otp_Sent_Enter_Reset_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Time Password(OTP) has been sent to your {0}. Please enter the same here to verify mobile number.
        /// </summary>
        internal static string Otp_Sent_Enter_Verify_Mobile {
            get {
                return ResourceManager.GetString("Otp_Sent_Enter_Verify_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;span&gt;Remember Browser?&lt;/span&gt;.
        /// </summary>
        internal static string RememberBrowser {
            get {
                return ResourceManager.GetString("RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend OTP.
        /// </summary>
        internal static string ResendOTP {
            get {
                return ResourceManager.GetString("ResendOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Verification.
        /// </summary>
        internal static string VerifyCodeTitle {
            get {
                return ResourceManager.GetString("VerifyCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify OTP.
        /// </summary>
        internal static string VerifyOTPTitle {
            get {
                return ResourceManager.GetString("VerifyOTPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Phone Number.
        /// </summary>
        internal static string VerifyPhoneNumber {
            get {
                return ResourceManager.GetString("VerifyPhoneNumber", resourceCulture);
            }
        }
    }
}
