//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuthoritySTS.LocalizationResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuthoritySTS.LocalizationResources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created a new account with password..
        /// </summary>
        internal static string ACCOUNT_CREATED {
            get {
                return ResourceManager.GetString("ACCOUNT_CREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        internal static string ACCOUNT_LOCKED_OUT {
            get {
                return ResourceManager.GetString("ACCOUNT_LOCKED_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is required..
        /// </summary>
        internal static string CONF_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("CONF_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code is not valid..
        /// </summary>
        internal static string COUNTRY_CODE_INVALID {
            get {
                return ResourceManager.GetString("COUNTRY_CODE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code is required..
        /// </summary>
        internal static string COUNTRY_CODE_REQUIRED {
            get {
                return ResourceManager.GetString("COUNTRY_CODE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email &apos;{0}&apos; is already taken..
        /// </summary>
        internal static string DUPLICATE_EMAIL {
            get {
                return ResourceManager.GetString("DUPLICATE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number already exist..
        /// </summary>
        internal static string DUPLICATE_PHONE {
            get {
                return ResourceManager.GetString("DUPLICATE_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid..
        /// </summary>
        internal static string EMAIL_NOT_VALID {
            get {
                return ResourceManager.GetString("EMAIL_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not verified..
        /// </summary>
        internal static string EMAIL_NOT_VERIFIED {
            get {
                return ResourceManager.GetString("EMAIL_NOT_VERIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        internal static string EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External authentication error..
        /// </summary>
        internal static string EXTERNAL_AUTH_ERROR {
            get {
                return ResourceManager.GetString("EXTERNAL_AUTH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email/mobile number..
        /// </summary>
        internal static string FORGET_PASSWORD_DATA_INVALID {
            get {
                return ResourceManager.GetString("FORGET_PASSWORD_DATA_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name is required..
        /// </summary>
        internal static string FULLNAME_REQUIRED {
            get {
                return ResourceManager.GetString("FULLNAME_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid code..
        /// </summary>
        internal static string INVALID_CODE {
            get {
                return ResourceManager.GetString("INVALID_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login attempt..
        /// </summary>
        internal static string INVALID_LOGIN {
            get {
                return ResourceManager.GetString("INVALID_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number is not valid..
        /// </summary>
        internal static string MOBILE_NOT_VALID {
            get {
                return ResourceManager.GetString("MOBILE_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number is required..
        /// </summary>
        internal static string MOBILE_REQUIRED {
            get {
                return ResourceManager.GetString("MOBILE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is required..
        /// </summary>
        internal static string NEW_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("NEW_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security code is: {0}.
        /// </summary>
        internal static string NOTF_2FA_BODY {
            get {
                return ResourceManager.GetString("NOTF_2FA_BODY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Code.
        /// </summary>
        internal static string NOTF_2FA_SUB {
            get {
                return ResourceManager.GetString("NOTF_2FA_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OTP to change password is: {0}.
        /// </summary>
        internal static string NOTF_OTP_PASS {
            get {
                return ResourceManager.GetString("NOTF_OTP_PASS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your OTP to verify mobile number is: {0}.
        /// </summary>
        internal static string NOTF_OTP_VERIFY_PHONE {
            get {
                return ResourceManager.GetString("NOTF_OTP_VERIFY_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        internal static string NOTF_RESET_PASS_SUB {
            get {
                return ResourceManager.GetString("NOTF_RESET_PASS_SUB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is required..
        /// </summary>
        internal static string OLD_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("OLD_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP expired..
        /// </summary>
        internal static string OTP_EXPIRED {
            get {
                return ResourceManager.GetString("OTP_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP does not match..
        /// </summary>
        internal static string OTP_MISMATCH {
            get {
                return ResourceManager.GetString("OTP_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP is required..
        /// </summary>
        internal static string OTP_REQUIRED {
            get {
                return ResourceManager.GetString("OTP_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and confirm password do not match..
        /// </summary>
        internal static string PASS_CONF_NOT_SAME {
            get {
                return ResourceManager.GetString("PASS_CONF_NOT_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        internal static string PASS_NEW_CONF_NOT_SAME {
            get {
                return ResourceManager.GetString("PASS_NEW_CONF_NOT_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have atleast one number character..
        /// </summary>
        internal static string PASSWORD_DIGIT {
            get {
                return ResourceManager.GetString("PASSWORD_DIGIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Password Length Required is {0}.
        /// </summary>
        internal static string PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have atleast one lowercase character..
        /// </summary>
        internal static string PASSWORD_LOWERCASE {
            get {
                return ResourceManager.GetString("PASSWORD_LOWERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not reuse old password..
        /// </summary>
        internal static string PASSWORD_OLDPASS_SAME {
            get {
                return ResourceManager.GetString("PASSWORD_OLDPASS_SAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        internal static string PASSWORD_RESET {
            get {
                return ResourceManager.GetString("PASSWORD_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords cannot be all the same character..
        /// </summary>
        internal static string PASSWORD_SAMECHAR {
            get {
                return ResourceManager.GetString("PASSWORD_SAMECHAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have atleast one special character..
        /// </summary>
        internal static string PASSWORD_SYMBOL {
            get {
                return ResourceManager.GetString("PASSWORD_SYMBOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must have atleast one uppercase character..
        /// </summary>
        internal static string PASSWORD_UPPERCASE {
            get {
                return ResourceManager.GetString("PASSWORD_UPPERCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile number is not verified..
        /// </summary>
        internal static string PHONE_NOT_VERIFIED {
            get {
                return ResourceManager.GetString("PHONE_NOT_VERIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requires Two Factor Authentication..
        /// </summary>
        internal static string REQUIRE_2FA {
            get {
                return ResourceManager.GetString("REQUIRE_2FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has expired. please login again to continue..
        /// </summary>
        internal static string SESSION_EXPIRED {
            get {
                return ResourceManager.GetString("SESSION_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is not valid. Please login again to continue..
        /// </summary>
        internal static string TOKEN_INVALID {
            get {
                return ResourceManager.GetString("TOKEN_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load user.
        /// </summary>
        internal static string UNABLE_LOAD_USER {
            get {
                return ResourceManager.GetString("UNABLE_LOAD_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown userid..
        /// </summary>
        internal static string UNKNOWN_ID {
            get {
                return ResourceManager.GetString("UNKNOWN_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User logged in..
        /// </summary>
        internal static string USER_LOGGED_IN {
            get {
                return ResourceManager.GetString("USER_LOGGED_IN", resourceCulture);
            }
        }
    }
}
